describe('My First Test', () => {
  it('Visits the Claims sites', () => {
    cy.visit('https://claims-int.petplan.co.uk/')
  })
  it('Create claims ', () => {
   cy.get('#onetrust-accept-btn-handler').click()
   //cy.wait(3000)
//   cy.intercept('/new-condition-label/*').as('newconditionlabel')
//   cy.wait('@newconditionlabel')
   cy.get('#new-condition-label').click()
   cy.get('#title').select('Mrs')
   cy.get('#firstName').type('Anuja')
   cy.get('#lastName').type('Nair')
   cy.get('#email').type('anuja.nair@allianz.com')
   cy.get('#postCode').type('GU1 1SB')
   cy.get('#findAddressBtn').click()
   cy.get('#name').type('Hulk')
   cy.get('#type-dog-label').click()
  // cy.wait(3000)
   cy.get('#pedigreeBreed').type('Aberdeen Terrier')
   cy.get('#sex-male-label').click()
   cy.get('#dateOfBirthRelmonth').select('January')
   cy.get('#dateOfBirthRelyear').select('2019')
   cy.get('#dateOfOwnershipRelmonth').select('January')
   cy.get('#dateOfOwnershipRelyear').select('2019')
   cy.get('#death-no-label').click()
   cy.get('#startDateRelday').select('01')
   cy.get('#startDateRelmonth').select('January')
   cy.get('#startDateRelyear').select('2020')
   cy.get('#description').type('Test')
   cy.get('#vetPostCode').type('TW8 9DX')
   cy.get('#findVetAddressBtn > span').click()
   cy.get('#addressReadoutVet', { timeout: 50000 }).should('be.visible');
   //cy.wait(5000)
//   cy.intercept('/addressReadoutVet/*').as('vetaddress')
//   cy.wait('@vetaddress')
   cy.get('#memberOfPlan-yes-label').click()
   cy.get(':nth-child(1) > .radio-group-checkbox').click()
   cy.get('.sa-checkbox').click()
   cy.get('.btn-primary').click()
   //cy.wait(5000)
//   cy.intercept('/.offset-lg4 > h1/*').as('thankyoumessage')
//   cy.wait('@thankyoumessage')
    cy
      .get('.offset-lg4 > h1')
      .should('have.text', 'Thank you')
    })
})
